spring:
  # datasource:
  #   url: jdbc:sqlserver://localhost:1433;database=library;encrypt=true;trustServerCertificate=true;
  #   username: sa
  #   password: Sa123456
  #   driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  datasource:
    url: jdbc:h2:mem:books
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #initialization-mode: always
    #schema: schema.sql
    #data: data.sql
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      #authentication-database: admin
      #username: root
      #password: root
      database: library2
      port: 27017
      host: localhost
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
mongock:
  # runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"    # mongock + spring shell https://bit.ly/3C28YX4
  change-logs-scan-package:
    - ru.otus.spring14books.mongock.changelog
