spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=library;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Sa123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      #authentication-database: admin
      #username: root
      #password: root
      database: library2
      port: 27017
      host: localhost
mongock:
  # runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"    # mongock + spring shell https://bit.ly/3C28YX4
  change-logs-scan-package:
    - ru.otus.spring14books.mongock.changelog