DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    FULLNAME VARCHAR(255)
);
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE      VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID)
);