spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books
    username: library
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true