spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=library;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Sa123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  jmx:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
      defaults:
        enabled: true
